--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: self if envs.empty? || envs.include?(environment.to_sym)
comment: 
- !ruby/struct:SM::Flow::P 
  body: Set configuration options for Sinatra and/or the app. Allows scoping of settings for certain environments.
full_name: Sinatra::Base::configure
is_singleton: true
name: configure
params: (*envs, &block) {|self if envs.empty? || envs.include?(environment.to_sym)| ...}
visibility: public
