--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "Deprecated. Use: configure"
full_name: Sinatra::Default::configures
is_singleton: true
name: configures
params: (*args, &block)
visibility: public
