--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: The top-level Application. All DSL methods executed on main are delegated to this class.
constants: []

full_name: Sinatra::Application
includes: []

instance_methods: []

name: Application
superclass: Default
