--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "Deprecated. Use: Sinatra::Application.reset!"
full_name: Sinatra::application=
is_singleton: true
name: application=
params: (value)
visibility: public
